branch-defaults:
  default:
    environment: null
    group_suffix: null
  master:
    environment: Climbing-prediction-env
environment-defaults:
  Climbing-prediction-env:
    branch: null
    repository: null
global:
  application_name: climbing-prediction
  branch: null
  default_ec2_keyname: null
  default_platform: Python 3.13 running on 64bit Amazon Linux 2023
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
